require "../../design_tokens"

module UI
  module DesignTokens
    # Emits a CSS file from a `UI::DesignTokens::Tokens` instance.
    #
    # The output is deterministic: same input bytes → same output bytes.
    # Canonical CSS custom-property prefix is `--ap-*`. The previously-shipped
    # `--amber-*` alias block is NOT emitted in this phase or any later
    # phase — the prefix change to `--ap-*` is total (see implementation.md
    # §4.1 and the Architect's note in handoff/phase-01-architect-scope-deferral-2026-05-20.md).
    #
    # Output structure:
    #   :root { …light tokens… }
    #   @media (prefers-color-scheme: dark) { :root { …dark tokens… } }
    #   [data-ap-theme="light"] { …light… }
    #   [data-ap-theme="dark"]  { …dark… }
    module WebGenerator
      extend self

      HEADER = "/* GENERATED by UI::DesignTokens::WebGenerator. Do not edit by hand. */\n"

      def generate(tokens : Tokens) : String
        String.build do |io|
          io << HEADER
          emit_root_block(io, tokens, :light)
          io << "\n"
          emit_media_dark(io, tokens)
          io << "\n"
          emit_data_theme(io, tokens, :light)
          io << "\n"
          emit_data_theme(io, tokens, :dark)
          io << "\n"
          emit_supports_fallback(io, tokens)
        end
      end

      private def emit_root_block(io : IO, tokens : Tokens, scheme : Symbol) : Nil
        io << ":root {\n"
        io << "  color-scheme: light dark;\n\n"
        emit_color_vars(io, scheme == :dark ? tokens.colors_dark : tokens.colors_light, indent: "  ")
        io << "\n"
        emit_spacing_vars(io, tokens.spacing, indent: "  ")
        io << "\n"
        emit_type_vars(io, tokens.type, indent: "  ")
        io << "\n"
        emit_radius_vars(io, tokens.radius, indent: "  ")
        io << "\n"
        emit_shadow_vars(io, tokens.shadow, indent: "  ")
        io << "\n"
        emit_motion_vars(io, tokens.motion, indent: "  ")
        io << "\n"
        emit_breakpoint_vars(io, tokens.breakpoints, indent: "  ")
        io << "\n"
        emit_material_vars(io, tokens.material, indent: "  ")
        io << "\n"
        io << "  --ap-touch-target-min: #{format_px(tokens.touch_target_minimum_px)};\n"
        io << "}\n"
      end

      # Phase 5: glass material custom properties.
      #
      # `--ap-material-intensity` is the brand-declaration-time scalar (default
      # 1.0). Per-step blur radii are emitted as `calc()` expressions referencing
      # the intensity custom property so a brand-overridden Tokens instance
      # produces an entirely different CSS bundle with no per-call-site math.
      # Opacity and saturation are not scaled by intensity per the documented
      # adapter_cardinality contract (brief.yml row 2).
      private def emit_material_vars(io : IO, material : Material, indent : String) : Nil
        io << "#{indent}/* glass material — Phase 5 */\n"
        intensity_clamped = material.intensity.clamp(0.1, 3.0)
        io << "#{indent}--ap-material-intensity: #{format_number(intensity_clamped)};\n"
        emit_material_step_vars(io, "ultra-thin", material.ultra_thin, indent)
        emit_material_step_vars(io, "thin", material.thin, indent)
        emit_material_step_vars(io, "regular", material.regular, indent)
        emit_material_step_vars(io, "thick", material.thick, indent)
        emit_material_step_vars(io, "chrome", material.chrome, indent)
      end

      private def emit_material_step_vars(io : IO, name : String, step : MaterialStep, indent : String) : Nil
        # Blur radius scales with intensity via calc(); fallback to "1"
        # via the var() default so static-CSS consumers without the
        # intensity declaration still resolve a sensible value.
        io << "#{indent}--ap-material-blur-#{name}: calc(#{format_px(step.blur_radius)} * var(--ap-material-intensity, 1));\n"
        io << "#{indent}--ap-material-opacity-#{name}: #{format_number(step.opacity)};\n"
        io << "#{indent}--ap-material-saturation-#{name}: #{format_number(step.saturation)};\n"
      end

      # `@supports not (backdrop-filter)` fallback block. Browsers without
      # `backdrop-filter` (and without `-webkit-backdrop-filter`) get a
      # solid-tinted panel at the documented per-step opacity. The fallback
      # uses HIGH opacity (90..98%) on purpose — without backdrop blur, a
      # low-opacity fill reads as transparent muddiness rather than as a
      # glass surface.
      #
      # The fallback binds to the `.ap-glass--<step>` class names the web
      # renderer emits alongside the inline-style live path. Inline style
      # still wins for browsers that support the live path; the class
      # selector is purely for the fallback.
      private def emit_supports_fallback(io : IO, tokens : Tokens) : Nil
        io << "@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {\n"
        io << "  .ap-glass--ultra-thin { background: color-mix(in oklch, var(--ap-color-surface-panel) 90%, transparent); }\n"
        io << "  .ap-glass--thin       { background: color-mix(in oklch, var(--ap-color-surface-panel) 92%, transparent); }\n"
        io << "  .ap-glass--regular    { background: color-mix(in oklch, var(--ap-color-surface-panel) 94%, transparent); }\n"
        io << "  .ap-glass--thick      { background: color-mix(in oklch, var(--ap-color-surface-panel) 96%, transparent); }\n"
        io << "  .ap-glass--chrome     { background: color-mix(in oklch, var(--ap-color-surface-panel) 98%, transparent); }\n"
        io << "}\n"
      end

      private def emit_media_dark(io : IO, tokens : Tokens) : Nil
        io << "@media (prefers-color-scheme: dark) {\n"
        io << "  :root {\n"
        emit_color_vars(io, tokens.colors_dark, indent: "    ")
        io << "  }\n"
        io << "}\n"
      end

      private def emit_data_theme(io : IO, tokens : Tokens, scheme : Symbol) : Nil
        attr_value = scheme == :dark ? "dark" : "light"
        palette = scheme == :dark ? tokens.colors_dark : tokens.colors_light
        io << "[data-ap-theme=\"#{attr_value}\"] {\n"
        emit_color_vars(io, palette, indent: "  ")
        io << "}\n"
      end

      private def emit_color_vars(io : IO, palette : ColorPalette, indent : String) : Nil
        io << "#{indent}/* colors — canonical OKLCH plus baked RGB fallback */\n"
        palette.to_h.each do |name, color|
          io << "#{indent}--ap-color-#{name}: #{color.to_oklch_css};\n"
          io << "#{indent}--ap-color-#{name}-rgb: #{color.to_rgb_triple_css};\n"
        end
      end

      private def emit_spacing_vars(io : IO, scale : SpacingScale, indent : String) : Nil
        io << "#{indent}/* spacing — rem */\n"
        scale.to_h.each do |key, value|
          rendered = key == "px" ? "1px" : format_rem(value)
          io << "#{indent}--ap-space-#{key}: #{rendered};\n"
        end
      end

      private def emit_type_vars(io : IO, scale : TypeScale, indent : String) : Nil
        io << "#{indent}/* type */\n"
        io << "#{indent}--ap-font-sans: #{scale.family_sans};\n"
        io << "#{indent}--ap-font-display: #{scale.family_display};\n"
        io << "#{indent}--ap-font-mono: #{scale.family_mono};\n"
        emit_type_step(io, "caption", scale.caption, indent)
        emit_type_step(io, "body", scale.body, indent)
        emit_type_step(io, "body-emph", scale.body_emph, indent)
        emit_type_step(io, "title", scale.title, indent)
        emit_type_step(io, "headline", scale.headline, indent)
        emit_type_step(io, "display", scale.display, indent)
      end

      private def emit_type_step(io : IO, name : String, step : TypeStep, indent : String) : Nil
        io << "#{indent}--ap-type-#{name}-size: #{format_rem(step.size)};\n"
        io << "#{indent}--ap-type-#{name}-line-height: #{format_number(step.line_height)};\n"
        io << "#{indent}--ap-type-#{name}-weight: #{step.weight};\n"
        io << "#{indent}--ap-type-#{name}-tracking: #{format_em(step.tracking)};\n"
      end

      private def emit_radius_vars(io : IO, scale : RadiusScale, indent : String) : Nil
        io << "#{indent}/* radius */\n"
        io << "#{indent}--ap-radius-none: #{format_rem(scale.none)};\n"
        io << "#{indent}--ap-radius-xs: #{format_rem(scale.xs)};\n"
        io << "#{indent}--ap-radius-sm: #{format_rem(scale.sm)};\n"
        io << "#{indent}--ap-radius-md: #{format_rem(scale.md)};\n"
        io << "#{indent}--ap-radius-lg: #{format_rem(scale.lg)};\n"
        io << "#{indent}--ap-radius-xl: #{format_rem(scale.xl)};\n"
        io << "#{indent}--ap-radius-2xl: #{format_rem(scale.x2l)};\n"
        io << "#{indent}--ap-radius-card: #{format_rem(scale.card)};\n"
        io << "#{indent}--ap-radius-sheet: #{format_rem(scale.sheet)};\n"
        io << "#{indent}--ap-radius-avatar: #{format_rem(scale.avatar)};\n"
        io << "#{indent}--ap-radius-avatar-lg: #{format_rem(scale.avatar_lg)};\n"
        # The pill sentinel renders as a literal pixel size (9999px), not rem,
        # so we don't accidentally get a comically large rem-based render.
        io << "#{indent}--ap-radius-pill: 9999px;\n"
      end

      private def emit_shadow_vars(io : IO, scale : ShadowScale, indent : String) : Nil
        io << "#{indent}/* shadow */\n"
        io << "#{indent}--ap-shadow-flat: #{render_shadow(scale.flat)};\n"
        io << "#{indent}--ap-shadow-raised: #{render_shadow(scale.raised)};\n"
        io << "#{indent}--ap-shadow-floating: #{render_shadow(scale.floating)};\n"
        io << "#{indent}--ap-shadow-overlay: #{render_shadow(scale.overlay)};\n"
      end

      private def render_shadow(levels : Array(ShadowLevel)) : String
        return "none" if levels.empty?
        levels.map do |level|
          parts = [format_rem(level.offset_x), format_rem(level.offset_y), format_rem(level.blur)]
          parts << format_rem(level.spread) if level.spread != 0.0
          parts << level.color.to_oklch_css
          parts.join(' ')
        end.join(", ")
      end

      private def emit_motion_vars(io : IO, scale : MotionScale, indent : String) : Nil
        io << "#{indent}/* motion */\n"
        io << "#{indent}--ap-motion-duration-instant: #{scale.duration_instant_ms}ms;\n"
        io << "#{indent}--ap-motion-duration-fast: #{scale.duration_fast_ms}ms;\n"
        io << "#{indent}--ap-motion-duration-base: #{scale.duration_base_ms}ms;\n"
        io << "#{indent}--ap-motion-duration-slow: #{scale.duration_slow_ms}ms;\n"
        io << "#{indent}--ap-motion-ease-standard: #{scale.ease_standard};\n"
        io << "#{indent}--ap-motion-ease-emphasized: #{scale.ease_emphasized};\n"
        io << "#{indent}--ap-motion-spring: #{scale.spring};\n"
      end

      private def emit_breakpoint_vars(io : IO, scale : Breakpoints, indent : String) : Nil
        io << "#{indent}/* breakpoints — informational; actual breakpoints live in @media rules */\n"
        io << "#{indent}--ap-bp-sm: #{format_px(scale.sm)};\n"
        io << "#{indent}--ap-bp-md: #{format_px(scale.md)};\n"
        io << "#{indent}--ap-bp-lg: #{format_px(scale.lg)};\n"
        io << "#{indent}--ap-bp-xl: #{format_px(scale.xl)};\n"
        io << "#{indent}--ap-bp-2xl: #{format_px(scale.x2l)};\n"
      end

      private def format_rem(value : Float64) : String
        return "0rem" if value == 0.0
        "#{format_number(value)}rem"
      end

      private def format_px(value : Float64) : String
        if value == value.to_i.to_f
          "#{value.to_i}px"
        else
          "#{format_number(value)}px"
        end
      end

      private def format_em(value : Float64) : String
        "#{format_number(value)}em"
      end

      private def format_number(value : Float64) : String
        # Print without trailing zeros so 1.0 → "1", 1.55 → "1.55", 0.125 → "0.125".
        if value == value.to_i.to_f
          value.to_i.to_s
        else
          s = "%.6f" % value
          s = s.rstrip('0').rstrip('.')
          s.empty? ? "0" : s
        end
      end
    end
  end
end
