#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Generates docs/support-matrix.md from the sources of truth:
#   config/android_toolchain.env            the Android pins
#   .github/workflows/android-native.yml    the Android CI lanes
#   .github/workflows/apple-native.yml      the Apple CI lanes (when present)
#   config/apple_toolchain.env              the Apple pins (fork compiler, runner images)
#   samples/cross_platform/ios_host/project.yml   the iOS deployment target
#   swift/AssetPipelineSwiftKit/Package.swift     the SwiftKit platform floors
#   shard.yml                               the Crystal requirement
#   config/support_proof.yml                what has actually run, dated
#
#   ruby scripts/support_matrix.rb            # rewrite the document
#   ruby scripts/support_matrix.rb --check    # exit 1 when it is stale
#
# Runs on Ruby 2.6 and later; no gems beyond the standard library.
require "yaml"
require "date"

ROOT = File.expand_path("..", __dir__)
TARGET = File.join(ROOT, "docs", "support-matrix.md")

ANDROID_NAMES = {
  31 => "Android 12", 32 => "Android 12L", 33 => "Android 13", 34 => "Android 14",
  35 => "Android 15", 36 => "Android 16", 37 => "Android 17"
}.freeze

def read(path)
  File.read(File.join(ROOT, path))
end

# Psych 4 (Ruby 3.1+) makes load_file a safe load that rejects Date and
# aliases; Psych 3 (Ruby 2.6) does not. One explicit safe load behaves the
# same on both, and the ledger keeps its dates as strings.
def load_yaml(path)
  YAML.safe_load(File.read(path), permitted_classes: [Date], aliases: true)
end

def env_pins(path)
  pins = {}
  read(path).each_line do |line|
    line = line.strip
    next if line.empty? || line.start_with?("#")
    key, value = line.split("=", 2)
    pins[key] = value
  end
  pins
end

def android_name(api)
  major = api.to_s.split(".").first.to_i
  name = ANDROID_NAMES[major] || "Android (API #{major})"
  api.to_s.include?(".") ? "#{name} (SDK #{api})" : name
end

def triggers(workflow)
  on = workflow["on"] || workflow[true] # YAML 1.1 parsers read a bare `on:` as true
  keys = on.keys
  parts = []
  parts << "pull request" if keys.include?("pull_request")
  if keys.include?("push")
    branches = (on["push"] || {})["branches"]
    parts << (branches ? "push to #{branches.join(', ')}" : "push")
  end
  if keys.include?("schedule")
    crons = on["schedule"].map { |entry| entry["cron"] }
    parts << "schedule (#{crons.join('; ')} UTC)"
  end
  parts << "manual dispatch" if keys.include?("workflow_dispatch")
  parts.join(", ")
end

def load_workflow(path)
  full = File.join(ROOT, path)
  return nil unless File.exist?(full)
  load_yaml(full)
end

def table(headers, rows)
  lines = ["| #{headers.join(' | ')} |", "| #{headers.map { '---' }.join(' | ')} |"]
  rows.each { |row| lines << "| #{row.join(' | ')} |" }
  lines.join("\n")
end

pins = env_pins("config/android_toolchain.env")
apple_pins = File.exist?(File.join(ROOT, "config", "apple_toolchain.env")) ? env_pins("config/apple_toolchain.env") : {}
android = load_workflow(".github/workflows/android-native.yml")
apple = load_workflow(".github/workflows/apple-native.yml")
proof = load_yaml(File.join(ROOT, "config", "support_proof.yml"))["proofs"]
ios_project = load_yaml(File.join(ROOT, "samples", "cross_platform", "ios_host", "project.yml"))
ios_target = ios_project["options"]["deploymentTarget"]["iOS"]
swift_floors = read("swift/AssetPipelineSwiftKit/Package.swift").scan(/\.(iOS|macOS|watchOS)\(\.v(\d+)\)/).map { |os, v| "#{os} #{v}" }
crystal_requirement = read("shard.yml")[/^crystal:\s*['"]?([^'"\n]+)['"]?/, 1]

native = android["jobs"]["native"]
matrix_apis = native["strategy"]["matrix"]["api"].map(&:to_s)
gate = native["steps"].find { |step| step["name"] == "Native build, runtime and isolated failure gates" }
image = gate["env"]
min_sdk = pins["ANDROID_MIN_SDK"].to_i
newest_lane = matrix_apis.map(&:to_f).max

doc = +""
doc << "# Support matrix\n\n"
doc << "Generated by `ruby scripts/support_matrix.rb` from the pins, the workflows and\n"
doc << "`config/support_proof.yml`. Do not edit by hand: change a source, rerun the\n"
doc << "script, commit the result. CI runs it with `--check` and fails when this file\n"
doc << "is stale. What \"supported\" means, and how a new OS release enters this table,\n"
doc << "is in `docs/compatibility-policy.md`.\n\n"

doc << "## Android\n\n"
doc << "Supported runtimes: **#{android_name(min_sdk)} (API #{min_sdk}) through #{android_name(newest_lane == newest_lane.floor ? newest_lane.to_i : newest_lane)}**.\n"
doc << "The floor is `ANDROID_MIN_SDK`; the ceiling is the newest lane of the pull-request\n"
doc << "gate. API levels between the lanes are supported by policy and not exercised by\n"
doc << "CI; the newest released runtime is exercised nightly, not supported, until its\n"
doc << "lane is stable enough to join the gate.\n\n"
doc << "### Pins (`config/android_toolchain.env`)\n\n"
doc << table(%w[Pin Value Meaning], [
  ["`ANDROID_MIN_SDK`", pins["ANDROID_MIN_SDK"], "oldest runtime an app installs on (#{android_name(min_sdk)})"],
  ["`ANDROID_TARGET_SDK`", pins["ANDROID_TARGET_SDK"], "behavior level the app opts into (#{android_name(pins['ANDROID_TARGET_SDK'])})"],
  ["`ANDROID_COMPILE_SDK`", pins["ANDROID_COMPILE_SDK"], "platform the Kotlin and Java sources compile against"],
  ["`ANDROID_NATIVE_API`", pins["ANDROID_NATIVE_API"], "NDK API level the Crystal libraries link against"],
  ["`ANDROID_BUILD_TOOLS_VERSION`", pins["ANDROID_BUILD_TOOLS_VERSION"], "build tools"],
  ["`ANDROID_NDK_VERSION`", pins["ANDROID_NDK_VERSION"], "NDK"],
  ["`ANDROID_AGP_VERSION`", pins["ANDROID_AGP_VERSION"], "Android Gradle plugin"],
  ["`ANDROID_GRADLE_VERSION`", pins["ANDROID_GRADLE_VERSION"], "Gradle (wrapper and distribution SHA-256 pinned beside it)"],
  ["`ANDROID_KOTLIN_VERSION`", pins["ANDROID_KOTLIN_VERSION"], "Kotlin"],
  ["`ANDROID_JAVA_VERSION`", pins["ANDROID_JAVA_VERSION"], "JDK major"],
  ["`ANDROID_SUPPORTED_ABIS`", pins["ANDROID_SUPPORTED_ABIS"], "packaged ABIs (default `#{pins['ANDROID_DEFAULT_ABI']}`)"],
  ["`CRYSTAL_ANDROID_VERSION`", pins["CRYSTAL_ANDROID_VERSION"], "Crystal compiler every lane installs"]
])
doc << "\n\n### CI lanes (`.github/workflows/android-native.yml`)\n\n"
doc << "Runner `#{native['runs-on']}`, image `#{image['EMULATOR_TARGET']}` `#{image['EMULATOR_ARCH']}` `#{image['EMULATOR_PROFILE']}` "
doc << "(#{image['EMULATOR_CORES']} cores, #{image['EMULATOR_RAM_MB']} MB), one job per runtime, "
doc << "`make test-android` on each through `scripts/ci/android_emulator.sh`. Triggers: #{triggers(android)}.\n\n"
lane_rows = matrix_apis.map { |api|
  role = if api.to_i == min_sdk then "the floor (`ANDROID_MIN_SDK`)"
         elsif api.to_i == pins["ANDROID_TARGET_SDK"].to_i then "the target (`ANDROID_TARGET_SDK`)"
         elsif api.to_f == newest_lane then "the newest release; above the compile floor"
         else "an intermediate release"
         end
  [api, android_name(api), role]
}
if (next_runtime = pins["ANDROID_NEXT_RUNTIME"])
  next_workflow = load_workflow(".github/workflows/android-next.yml")
  where = next_workflow ? "`android-next.yml`, #{triggers(next_workflow)}; its own issue lane, never the pull-request gate" : "no android-next.yml yet"
  lane_rows << [next_runtime, android_name(next_runtime), "the newest released runtime (`ANDROID_NEXT_RUNTIME`): #{where}"]
end
doc << table(["Runtime API", "Android release", "Role"], lane_rows)
doc << "\n\n"

doc << "## Apple\n\n"
apple_rows = [
  ["iOS deployment target", ios_target, "`samples/cross_platform/ios_host/project.yml`"],
  ["SwiftKit platform floors", swift_floors.join(", "), "`swift/AssetPipelineSwiftKit/Package.swift`"]
]
unless apple_pins.empty?
  apple_rows << ["Compiler for the Apple targets", "`#{apple_pins["CRYSTAL_FORK_TAP"]}/#{apple_pins["CRYSTAL_FORK_FORMULA"]}` #{apple_pins["CRYSTAL_FORK_VERSION"]} (`#{apple_pins["CRYSTAL_FORK_COMMAND"]}`; stock Crystal has no iOS bindings)", "`config/apple_toolchain.env`"]
  apple_rows << ["Runner images", "current `#{apple_pins["APPLE_RUNNER_CURRENT"]}`, preview `#{apple_pins["APPLE_RUNNER_PREVIEW"]}`", "`config/apple_toolchain.env`"]
end
doc << table(%w[Pin Value Source], apple_rows)
doc << "\n\n"
if apple
  jobs = apple["jobs"]
  doc << "### CI lanes (`.github/workflows/apple-native.yml`)\n\nTriggers: #{triggers(apple)}.\n\n"
  rows = []
  jobs.each do |name, job|
    matrix = job.dig("strategy", "matrix")
    if matrix && matrix["include"]
      matrix["include"].each { |entry| rows << [name, entry["runner"] || entry["runs-on"] || job["runs-on"].to_s, entry["role"] || ""] }
    else
      rows << [name, job["runs-on"].to_s, ""]
    end
  end
  doc << table(%w[Job Runner Role], rows)
  doc << "\n\n"
else
  doc << "### CI lanes\n\nNo `apple-native.yml` yet; the Apple lanes are the next waypoint.\n\n"
end

doc << "## Web\n\n"
doc << table(%w[Pin Value Source], [
  ["Crystal requirement", "`#{crystal_requirement}`", "`shard.yml`"],
  ["Crystal on CI", pins["CRYSTAL_ANDROID_VERSION"], "`config/android_toolchain.env` (`CRYSTAL_ANDROID_VERSION`, installed by every lane)"],
  ["Runner", native["runs-on"], "the Android workflow's host-contracts step runs `spec/web/ui`"]
])
doc << "\n\n"

doc << "## Proofs (`config/support_proof.yml`)\n\n"
doc << "What has actually run, by date. A pin without a row here is a declaration, not a proof.\n\n"
doc << table(%w[Target Runtime What Date Evidence], proof.sort_by { |p| [p["target"], p["date"].to_s] }.map { |p|
  [p["target"], p["runtime"], p["what"], p["date"].to_s, p["evidence"]]
})
doc << "\n"

if ARGV.include?("--check")
  current = File.exist?(TARGET) ? File.read(TARGET) : ""
  if current == doc
    puts "docs/support-matrix.md is current"
  else
    warn "docs/support-matrix.md is stale; run: ruby scripts/support_matrix.rb"
    exit 1
  end
else
  File.write(TARGET, doc)
  puts "wrote docs/support-matrix.md"
end
