#!/usr/bin/env ruby
# frozen_string_literal: true
#
# view_parity_matrix.rb — generate docs/view-parity-matrix.md from the sources.
#
# For every UI view class under src/ui/views, and for every renderer under
# src/ui/renderers, the table says whether the renderer visits the class and
# which of the class's declared attributes that visit reads, directly or
# through the renderer's shared attribute helpers. Counts come from the code,
# not from a hand-kept list; rerun after changing a view or a renderer:
#
#   ruby scripts/view_parity_matrix.rb            # rewrite the document
#   ruby scripts/view_parity_matrix.rb --check    # exit 1 when it is stale
#
# A read is evidence that the renderer consults an attribute, not proof that
# it honors every value; the per-platform tier documents and device suites
# carry that proof. Attributes a class inherits are counted with it.
require "set"

ROOT = File.expand_path("..", __dir__)
VIEWS_DIR = File.join(ROOT, "src", "ui", "views")
# Each platform's sources: the renderer plus the support files its visits
# delegate to (the SwiftKit populators for the Apple platforms, the Android
# and web helpers for theirs). Reads are followed through all of them.
RENDERERS = [
  ["uikit_renderer", "iOS", ["native"]], ["android_renderer", "Android", ["android"]],
  ["appkit_renderer", "macOS", ["native"]], ["web_renderer", "Web", ["web"]], ["watchkit_renderer", "watchOS", ["native"]],
].freeze
# Helper classes that live beside the views but are not rendered on their own.
NON_VIEWS = %w[Item Node Token SwipeAction ActivityViewPresenter PopoverPresenter SheetPresenter SnackbarPresenter].freeze

Klass = Struct.new(:name, :base, :props, :file)

def scan_views
  classes = {}
  Dir[File.join(VIEWS_DIR, "*.cr")].sort.each do |file|
    src = File.read(file)
    src.scan(/^\s*class (\w+)(?:\s*<\s*([\w:]+))?/) do |name, base|
      next if name == "View"
      props = Set.new
      # Properties declared anywhere in the file belong to the classes in it;
      # view files hold one class each, plus small helpers.
      src.scan(/^\s*(?:property|getter|setter)\??\s+([a-z_][a-z0-9_?!]*)/) { |(p)| props << p.sub(/[?!]\z/, "") }
      src.scan(/^\s*def ([a-z_][a-z0-9_]*)=\(/) { |(p)| props << p }
      classes[name] = Klass.new(name, base.to_s.sub(/\AUI::/, ""), props, File.basename(file))
    end
  end
  # Inherit declared attributes down the class chain (TextField < ... < View).
  resolve = lambda do |name, seen = Set.new|
    k = classes[name]
    return Set.new unless k && seen.add?(name)
    k.props | resolve.call(k.base, seen)
  end
  classes.each_value { |k| k.props = resolve.call(k.name) }
  classes
end

def scan_renderer(name, support_dirs)
  files = [File.join(ROOT, "src", "ui", "renderers", "#{name}.cr")]
  support_dirs.each { |d| files += Dir[File.join(ROOT, "src", "ui", d, "**", "*.cr")].sort }
  src = files.map { |f| File.read(f) }.join("\n")
  # Every method in those sources: its parameters, its body, the attributes it
  # reads from a parameter named `view`, and the methods it calls.
  methods = {}
  src.scan(/^([ \t]*)(?:private )?def (?:self\.)?([a-z_][a-z0-9_?!]*)\(([^)]*)\)(.*?)(?=^\1(?:private )?def |\z)/m) do |_, method, params, body|
    reads = body.scan(/\bview\.([a-z_][a-z0-9_?]*)/).flatten.map { |a| a.sub(/\?\z/, "") }.to_set
    calls = body.scan(/\b([a-z_][a-z0-9_]*)\(/).flatten.to_set
    cls = params[/view : UI::(\w+)/, 1]
    (methods[method] ||= []) << { cls: cls, params: params, reads: reads, calls: calls }
  end
  # Reads reachable from a body through helpers that take the view along
  # (any called method with a `view` parameter), followed transitively.
  reachable = lambda do |entry, seen|
    total = entry[:reads].dup
    entry[:calls].each do |callee|
      next unless methods[callee] && seen.add?(callee)
      methods[callee].each { |e| total |= reachable.call(e, seen) if e[:params].include?("view") }
    end
    total
  end
  visits = {}
  (methods["visit"] || []).each do |entry|
    next unless entry[:cls]
    visits[entry[:cls]] = (visits[entry[:cls]] || Set.new) | reachable.call(entry, Set.new(["visit"]))
  end
  visits
end

classes = scan_views
views = classes.keys.reject { |n| NON_VIEWS.include?(n) }.sort
renderers = RENDERERS.to_h { |file, label, dirs| [label, scan_renderer(file, dirs)] }

lines = []
lines << "# View parity matrix"
lines << ""
lines << "Generated by `scripts/view_parity_matrix.rb` from `src/ui/views`, the"
lines << "renderers and their support directories; do not edit by hand. A cell reads `read/declared`:"
lines << "how many of the view's declared attributes (its own and inherited) the"
lines << "renderer's visit consults, directly or through its shared attribute"
lines << "helpers. `—` means the renderer has no visit for the view. A read is"
lines << "evidence the renderer consults the attribute, not proof it honors every"
lines << "value; the platform tier documents and device suites carry that proof."
lines << ""
both = views.count { |v| renderers["iOS"][v] && renderers["Android"][v] }
ios_only = views.select { |v| renderers["iOS"][v] && !renderers["Android"][v] }
android_only = views.select { |v| renderers["Android"][v] && !renderers["iOS"][v] }
neither = views.select { |v| !renderers["iOS"][v] && !renderers["Android"][v] }
lines << "**Phones.** #{views.size} view types; #{both} rendered on both iOS and Android;"
lines << "iOS only: #{ios_only.empty? ? 'none' : ios_only.join(', ')}; Android only: #{android_only.empty? ? 'none' : android_only.join(', ')};"
lines << "neither phone: #{neither.empty? ? 'none' : neither.join(', ')}."
lines << ""
lines << "| View | " + RENDERERS.map { |r| r[1] }.join(" | ") + " | iOS reads Android does not | Android reads iOS does not |"
lines << "| --- | " + RENDERERS.map { "---" }.join(" | ") + " | --- | --- |"
views.each do |v|
  props = classes[v].props
  cells = RENDERERS.map do |_, label, _dirs|
    attrs = renderers[label][v]
    attrs ? "#{(attrs & props).size}/#{props.size}" : "—"
  end
  i = renderers["iOS"][v] ? renderers["iOS"][v] & props : nil
  a = renderers["Android"][v] ? renderers["Android"][v] & props : nil
  gap_ios = (i && a) ? (i - a).sort.join(", ") : ""
  gap_android = (i && a) ? (a - i).sort.join(", ") : ""
  lines << "| `#{v}` | #{cells.join(' | ')} | #{gap_ios} | #{gap_android} |"
end
lines << ""
lines << "Views the sources declare but no phone renderer visits are listed above as"
lines << "`—` in both phone columns; the watchOS and macOS columns show where they"
lines << "belong. Attribute names in the last two columns are the concrete parity"
lines << "work: each is read by one phone renderer's visit and not by the other's."
doc = lines.join("\n") + "\n"

target = File.join(ROOT, "docs", "view-parity-matrix.md")
if (json_at = ARGV.index("--json"))
  require "json"
  File.write(ARGV[json_at + 1], JSON.pretty_generate(
    "views" => views.to_h { |v| [v, classes[v].props.to_a.sort] },
    "reads" => renderers.to_h { |label, vis| [label, vis.to_h { |v, a| [v, a.to_a.sort] }] }))
  ARGV.delete_at(json_at + 1); ARGV.delete_at(json_at)
end
if ARGV.include?("--check")
  current = File.exist?(target) ? File.read(target) : ""
  if current == doc
    puts "view-parity-matrix.md is current"
  else
    warn "view-parity-matrix.md is stale; run ruby scripts/view_parity_matrix.rb"
    exit 1
  end
else
  File.write(target, doc)
  puts "wrote #{target} (#{views.size} views)"
end
